[package]
name = "boc-talk"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = { version = "1.10.0", optional = true }

[features]
default = ["rayon"]
ref = []

[dev-dependencies]
crossbeam-channel = "0.5.14"
rand = "0.8.5"
